### ISSUE TITLE
what axe-core version and rules are being used?

### ISSUE THREAD

**Issue by jaimeiniesta** [accesslint/accesslint-cli.js#15]
Following the link on accesslint.com I get to the list of axe-core rules:

https://github.com/dequelabs/axe-core/blob/master/doc/rule-descriptions.md

There, some of them are marked as "not enabled by default", so, should I suppose that those are not used in accesslint-cli? If so, how can I enable them?

What version of axe-core are we using?

Thanks!

**Comment by tysongach** [comment]
Hey @jaimeiniesta!

We’re deprecating this project now that Deque released [axe-cli](https://github.com/dequelabs/axe-cli). They let use pass a `--rules` flag to specifically indicate which rules it should run.
