### ISSUE TITLE
system dependency

### ISSUE THREAD

**Issue by kriskowal** [accesslint/accesslint-cli.js#5]
@gozala has been kind enough to bequeath the `system` package to me. I will probably release a 0.2.0 or 1.0.0 for a new project soon. This project should continue to depend on version ^0.1.0 to function or remove the dependency.

**Comment by tysongach** [comment]
Closing; this project is no longer maintained now that [axe-cli](https://github.com/dequelabs/axe-cli) exists.

Thanks for the heads up, @kriskowal!
